import React, { useState, useEffect } from 'react';
import { RefreshCw, Copy, Share2, Heart, Volume2, Check, Sparkles, Filter, AlertTriangle, Lightbulb, Compass } from 'lucide-react';

interface AIQuoteData {
  id: string;
  quote: string;
  author: string;
  category: string;
  explanation?: string;
  actionTip?: string;
  createdAt?: string;
}

export const QuotesSection: React.FC = () => {
  const [currentQuote, setCurrentQuote] = useState<AIQuoteData | null>(null);
  const [selectedCategory, setSelectedCategory] = useState<string>('Success');
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);
  const [speaking, setSpeaking] = useState<boolean>(false);
  const [favorites, setFavorites] = useState<string[]>(() => {
    try {
      return JSON.parse(localStorage.getItem('smilespark_favorites') || '[]');
    } catch {
      return [];
    }
  });

  const categories = [
    'Success',
    'Study',
    'Coding',
    'Business',
    'Life',
    'Health',
    'Leadership',
    'Productivity',
    'Self-Confidence',
  ];

  useEffect(() => {
    generateAIQuote(selectedCategory);
  }, [selectedCategory]);

  const generateAIQuote = async (category: string) => {
    try {
      setLoading(true);
      setError(null);
      const res = await fetch('/api/ai/quote', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ category }),
      });

      let data: any = null;
      try {
        data = await res.json();
      } catch {
        setError('Server temporarily busy. Please click Retry in a moment.');
        return;
      }

      if (res.ok && data?.success && data?.data) {
        setCurrentQuote(data.data);
      } else {
        setError(data?.message || 'AI Engine rate limit reached. Please wait a moment and click Retry.');
      }
    } catch (err: any) {
      console.error('Error fetching AI quote:', err);
      setError('Connection issue or AI service unavailable. Please retry.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!currentQuote) return;
    const textToCopy = `"${currentQuote.quote}" — ${currentQuote.author}`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = () => {
    if (!currentQuote) return;
    if (navigator.share) {
      navigator.share({
        title: 'SmileSpark AI Quote',
        text: `"${currentQuote.quote}" — ${currentQuote.author}`,
        url: window.location.href,
      }).catch(() => {});
    } else {
      handleCopy();
    }
  };

  const toggleFavorite = (id: string) => {
    let updated: string[];
    if (favorites.includes(id)) {
      updated = favorites.filter((favId) => favId !== id);
    } else {
      updated = [...favorites, id];
    }
    setFavorites(updated);
    localStorage.setItem('smilespark_favorites', JSON.stringify(updated));
  };

  const handleSpeak = () => {
    if (!currentQuote) return;
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(
        `${currentQuote.quote} by ${currentQuote.author}`
      );
      utterance.rate = 0.95;
      utterance.onstart = () => setSpeaking(true);
      utterance.onend = () => setSpeaking(false);
      window.speechSynthesis.speak(utterance);
    }
  };

  return (
    <section className="py-12 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
      {/* Title */}
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/30 text-indigo-700 dark:text-indigo-400 text-xs font-bold uppercase tracking-wider mb-2">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Real-Time AI Wisdom</span>
        </div>
        <h2 className="text-3xl font-black text-slate-900 dark:text-white">
          AI Motivational Quotes
        </h2>
        <p className="mt-2 text-sm text-slate-600 dark:text-slate-400 max-w-xl mx-auto">
          Every quote is freshly generated by Advanced AI in real time, accompanied by practical action tips and deep insights.
        </p>
      </div>

      {/* Category Pills */}
      <div className="flex items-center sm:justify-center gap-2 overflow-x-auto sm:flex-wrap pb-2 sm:pb-0 mb-8 no-scrollbar">
        <Filter className="w-4 h-4 text-slate-400 mr-1 hidden sm:block shrink-0" />
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            disabled={loading}
            className={`px-3.5 py-2 rounded-xl text-xs sm:text-sm font-semibold whitespace-nowrap transition-all cursor-pointer shrink-0 min-h-[40px] flex items-center justify-center ${
              selectedCategory === cat
                ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/25 border border-indigo-400/30 font-bold'
                : 'bg-white dark:bg-white/5 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-white/10 hover:bg-slate-50 dark:hover:bg-white/10 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Quote Display Card */}
      {loading ? (
        <div className="p-8 sm:p-12 rounded-3xl bg-white dark:bg-white/5 backdrop-blur-xl border border-slate-200 dark:border-white/10 text-center animate-pulse space-y-4 shadow-sm dark:shadow-xl">
          <div className="flex justify-center items-center gap-2 text-indigo-600 dark:text-indigo-400 text-sm font-bold">
            <RefreshCw className="w-4 h-4 animate-spin" />
            <span>Generating AI wisdom for {selectedCategory}...</span>
          </div>
          <div className="h-8 bg-slate-100 dark:bg-white/10 rounded-xl w-3/4 mx-auto" />
          <div className="h-4 bg-slate-100 dark:bg-white/10 rounded-lg w-1/2 mx-auto" />
        </div>
      ) : error ? (
        <div className="p-8 rounded-3xl bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-500/20 text-center space-y-4">
          <AlertTriangle className="w-8 h-8 text-rose-500 mx-auto" />
          <p className="text-sm font-semibold text-rose-800 dark:text-rose-200">{error}</p>
          <button
            onClick={() => generateAIQuote(selectedCategory)}
            className="px-5 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold shadow-lg transition-all cursor-pointer"
          >
            Retry AI Generation
          </button>
        </div>
      ) : currentQuote ? (
        <div className="relative p-8 sm:p-12 rounded-3xl bg-white dark:bg-white/5 backdrop-blur-xl border border-slate-200 dark:border-white/10 shadow-sm dark:shadow-2xl transition-all space-y-6">
          {/* Top Category Badge & Audio */}
          <div className="flex items-center justify-between">
            <span className="px-3 py-1 rounded-lg bg-indigo-50 dark:bg-indigo-500/20 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-500/30 text-xs font-bold uppercase tracking-wider">
              {currentQuote.category}
            </span>

            <button
              onClick={handleSpeak}
              className={`p-2.5 rounded-xl transition-all cursor-pointer ${
                speaking
                  ? 'bg-indigo-600 text-white animate-bounce shadow-md shadow-indigo-500/40'
                  : 'bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-white/10 hover:text-slate-900 dark:hover:text-white'
              }`}
              title="Listen to Quote"
            >
              <Volume2 className="w-4 h-4" />
            </button>
          </div>

          {/* Quote Body */}
          <blockquote className="text-xl sm:text-3xl font-serif italic text-slate-900 dark:text-white leading-relaxed">
            "{currentQuote.quote}"
          </blockquote>

          {/* Explanation & Practical Action Tip */}
          {(currentQuote.explanation || currentQuote.actionTip) && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t border-slate-100 dark:border-white/10 text-xs">
              {currentQuote.explanation && (
                <div className="p-3.5 rounded-2xl bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/5 space-y-1">
                  <div className="flex items-center gap-1.5 font-bold text-indigo-600 dark:text-indigo-400">
                    <Compass className="w-3.5 h-3.5" />
                    <span>Deep Insight</span>
                  </div>
                  <p className="text-slate-700 dark:text-slate-300">{currentQuote.explanation}</p>
                </div>
              )}

              {currentQuote.actionTip && (
                <div className="p-3.5 rounded-2xl bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 space-y-1">
                  <div className="flex items-center gap-1.5 font-bold text-amber-700 dark:text-amber-400">
                    <Lightbulb className="w-3.5 h-3.5" />
                    <span>Action Tip</span>
                  </div>
                  <p className="text-slate-700 dark:text-slate-300">{currentQuote.actionTip}</p>
                </div>
              )}
            </div>
          )}

          <div className="mt-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-t border-slate-200 dark:border-white/10 pt-6">
            <cite className="not-italic font-extrabold text-sm sm:text-base text-indigo-600 dark:text-indigo-400">
              — {currentQuote.author}
            </cite>

            {/* Actions */}
            <div className="flex items-center gap-2 flex-wrap w-full sm:w-auto justify-end">
              <button
                onClick={() => toggleFavorite(currentQuote.id)}
                className={`p-2.5 rounded-xl transition-all cursor-pointer min-h-[44px] min-w-[44px] flex items-center justify-center ${
                  favorites.includes(currentQuote.id)
                    ? 'bg-rose-500 text-white shadow-md shadow-rose-500/30'
                    : 'bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:bg-rose-500/10 hover:text-rose-500'
                }`}
                title="Save Favorite"
              >
                <Heart className={`w-4 h-4 ${favorites.includes(currentQuote.id) ? 'fill-current' : ''}`} />
              </button>

              <button
                onClick={handleCopy}
                className="p-2.5 rounded-xl bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-white/10 transition-colors cursor-pointer min-h-[44px] min-w-[44px] flex items-center justify-center"
                title="Copy Quote"
              >
                {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
              </button>

              <button
                onClick={handleShare}
                className="p-2.5 rounded-xl bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-white/10 transition-colors cursor-pointer min-h-[44px] min-w-[44px] flex items-center justify-center"
                title="Share Quote"
              >
                <Share2 className="w-4 h-4" />
              </button>

              <button
                onClick={() => generateAIQuote(selectedCategory)}
                disabled={loading}
                className="flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs sm:text-sm font-bold shadow-lg shadow-indigo-600/25 transition-all cursor-pointer min-h-[44px] border border-indigo-400/30 flex-1 sm:flex-none"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
                <span>Generate New Quote</span>
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </section>
  );
};
